/* automatically generated by rust-bindgen 0.60.1 */

pub const PCAPNG_VERSION_MAJOR: u32 = 1;
pub const PCAPNG_VERSION_MINOR: u32 = 0;
pub const PCAPNG_BYTE_ORDER_MAGIC: u32 = 439041101;
pub const PCAPNG_INTERFACE_DESCRIPTION_BLOCK: u32 = 1;
pub const PCAPNG_PACKET_BLOCK: u32 = 2;
pub const PCAPNG_SIMPLE_PACKET_BLOCK: u32 = 3;
pub const PCAPNG_NAME_RESOLUTION_BLOCK: u32 = 4;
pub const PCAPNG_INTERFACE_STATISTICS_BLOCK: u32 = 5;
pub const PCAPNG_ENHANCED_PACKET_BLOCK: u32 = 6;
pub const PCAPNG_IRIG_TIMESTAMP_BLOCK: u32 = 7;
pub const PCAPNG_ARINC_429_AFDX_ENCAP_BLOCK: u32 = 8;
pub const PCAPNG_SYSTEMD_JOURNAL_EXPORT_BLOCK: u32 = 9;
pub const PCAPNG_DECRYPTION_SECRETS_BLOCK: u32 = 10;
pub const PCAPNG_HONE_PROJECT_MACHINE_INFO_BLOCK: u32 = 257;
pub const PCAPNG_HONE_PROJECT_CONNECTION_EVENT_BLOCK: u32 = 258;
pub const PCAPNG_SYSDIG_MACHINE_INFO_BLOCK: u32 = 513;
pub const PCAPNG_SYSDIG_PROCESS_INFO_V1_BLOCK: u32 = 514;
pub const PCAPNG_SYSDIG_FD_LIST_BLOCK: u32 = 515;
pub const PCAPNG_SYSDIG_EVENT_BLOCK: u32 = 516;
pub const PCAPNG_SYSDIG_INTERFACE_LIST_BLOCK: u32 = 517;
pub const PCAPNG_SYSDIG_USER_LIST_BLOCK: u32 = 518;
pub const PCAPNG_SYSDIG_PROCESS_INFO_V2_BLOCK: u32 = 519;
pub const PCAPNG_SYSDIG_EVENT_WITH_FLAGS_BLOCK: u32 = 520;
pub const PCAPNG_SYSDIG_PROCESS_INFO_V3_BLOCK: u32 = 521;
pub const PCAPNG_SYSDIG_PROCESS_INFO_V4_BLOCK: u32 = 528;
pub const PCAPNG_SYSDIG_PROCESS_INFO_V5_BLOCK: u32 = 529;
pub const PCAPNG_SYSDIG_PROCESS_INFO_V6_BLOCK: u32 = 530;
pub const PCAPNG_SYSDIG_PROCESS_INFO_V7_BLOCK: u32 = 531;
pub const PCAPNG_CUSTOM_DATA_BLOCK: u32 = 2989;
pub const PCAPNG_CUSTOM_DATA_BLOCK_NOCOPY: u32 = 1073744813;
pub const PCAPNG_SECTION_HEADER_BLOCK: u32 = 168627466;
pub const PCAPNG_TLS_KEY_LOG: u32 = 1414288203;
pub const PCAPNG_WIREGUARD_KEY_LOG: u32 = 1464290124;
pub const PCAPNG_ZIGBEE_NWK_KEY: u32 = 1515083595;
pub const PCAPNG_ZIGBEE_APS_KEY: u32 = 1514229843;
pub const PCAPNG_BLOCK_TYPE_AND_SIZE_LENGTH: u32 = 8;

pub type size_t = ::std::os::raw::c_ulong;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type FILE = libc::FILE;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}

pub type _IO_lock_t = ::std::os::raw::c_void;

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct _pcapng_custom_data_block_light_t {
    pub pen: u32,
}

pub type pcapng_custom_data_block_light_t = _pcapng_custom_data_block_light_t;

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct _pcapng_section_header_block_light_t {
    pub magic: u32,
    pub major_version: u16,
    pub minor_version: u16,
    pub section_length: u64,
}

pub type pcapng_section_header_block_light_t = _pcapng_section_header_block_light_t;

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct _pcapng_interface_description_block_light_t {
    pub linktype: u16,
    pub reserved: u16,
    pub snaplen: u32,
}

pub type pcapng_interface_description_block_light_t = _pcapng_interface_description_block_light_t;

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct _pcapng_enhanced_packet_block_light_t {
    pub interface_id: u32,
    pub timestamp_high: u32,
    pub timestamp_low: u32,
    pub captured_packet_length: u32,
    pub original_packet_length: u32,
}

pub type pcapng_enhanced_packet_block_light_t = _pcapng_enhanced_packet_block_light_t;

extern "C" {
    pub fn libpcapng_section_header_block_write(outbuf: *mut ::std::os::raw::c_uchar) -> size_t;
}

extern "C" {
    pub fn libpcapng_section_header_block_size() -> size_t;
}

extern "C" {
    pub fn libpcapng_section_header_block_read(
        inbuf: *mut ::std::os::raw::c_uchar,
        inbuf_len: size_t,
    ) -> *mut pcapng_section_header_block_light_t;
}

extern "C" {
    pub fn libpcapng_interface_description_block_write(
        snaplen: u32,
        outbuf: *mut ::std::os::raw::c_uchar,
    ) -> size_t;
}

extern "C" {
    pub fn libpcapng_interface_description_block_size() -> size_t;
}

extern "C" {
    pub fn libpcapng_interface_description_block_read(
        inbuf: *mut ::std::os::raw::c_uchar,
        inbuf_len: size_t,
    ) -> *mut pcapng_interface_description_block_light_t;
}

extern "C" {
    pub fn libpcapng_enhanced_packet_block_write_time(
        packet: *const ::std::os::raw::c_uchar,
        packet_len: size_t,
        timestamp_high: u32,
        timestamp_low: u32,
        outbuf: *mut ::std::os::raw::c_uchar,
    ) -> size_t;
}

extern "C" {
    pub fn libpcapng_enhanced_packet_block_write(
        packet: *const ::std::os::raw::c_uchar,
        packet_len: size_t,
        outbuf: *mut ::std::os::raw::c_uchar,
    ) -> size_t;
}

extern "C" {
    pub fn libpcapng_enhanced_packet_block_size(packet_len: size_t) -> size_t;
}

extern "C" {
    pub fn libpcapng_enhanced_packet_block_read(
        inbuf: *mut ::std::os::raw::c_uchar,
        inbuf_len: size_t,
    ) -> *mut pcapng_enhanced_packet_block_light_t;
}

extern "C" {
    pub fn libpcapng_custom_data_block_write(
        pen: u32,
        data: *const ::std::os::raw::c_uchar,
        data_len: size_t,
        outbuf: *mut ::std::os::raw::c_uchar,
    ) -> size_t;
}

extern "C" {
    pub fn libpcapng_custom_data_block_size(data_len: size_t) -> size_t;
}

extern "C" {
    pub fn libpcapng_custom_data_block_read(
        inbuf: *mut ::std::os::raw::c_uchar,
        inbuf_len: size_t,
    ) -> *mut pcapng_custom_data_block_light_t;
}

extern "C" {
    pub fn libpcapng_custom_data_block_start_offset() -> u32;
}

extern "C" {
    pub fn libpcapng_custom_data_block_data_length(block_total_length: u32) -> u32;
}

extern "C" {
    pub fn libpcapng_write_header_to_file(outfile: *mut FILE) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn libpcapng_write_enhanced_packet_to_file(
        outfile: *mut FILE,
        packet: *mut ::std::os::raw::c_uchar,
        packet_size: size_t,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn libpcapng_write_enhanced_packet_with_time_to_file(
        outfile: *mut FILE,
        packet: *mut ::std::os::raw::c_uchar,
        packet_size: size_t,
        timestamp: u32,
    ) -> ::std::os::raw::c_int;
}

pub type foreach_pcapng_block_cb = ::std::option::Option<
    unsafe extern "C" fn(
        block_counter: u32,
        block_type: u32,
        block_total_length: u32,
        data: *mut ::std::os::raw::c_uchar,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;

extern "C" {
    pub fn libpcapng_fp_read(
        fp: *mut FILE,
        pcapng_block_cb: foreach_pcapng_block_cb,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn libpcapng_file_read(
        filename: *mut ::std::os::raw::c_char,
        pcapng_block_cb: foreach_pcapng_block_cb,
        userdata: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn libpcapng_file_read_debug(
        filename: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}

extern "C" {
    pub fn libpcapng_padded_count(
        data: *mut ::std::os::raw::c_uchar,
        data_len: u32,
    ) -> ::std::os::raw::c_int;
}
