name: Rust

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install build-essential cmake libwandio1 libwandio1-dev pybind11-dev python3-pybind11
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish Binding Crate
      uses: katyo/publish-crates@v2
      with:
          path: './libpcapng-sys'
          args: --no-verify
          dry-run: true
    - name: Publish API Crate
      uses: katyo/publish-crates@v2
      with:
          path: '.'
          args: --no-verify
          dry-run: true
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
